env:
  mode: dev
service:
  name: mp.service
  version: v1
server:
  http:
    addr: 0.0.0.0:7008
    timeout: 10s
  grpc:
    addr: 0.0.0.0:7101
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:rootroot@tcp(127.0.0.1:3306)/it-ku?parseTime=true&collation=utf8mb4_unicode_ci&loc=Asia%2FShanghai&charset=utf8mb4
  redis:
    addr: 127.0.0.1:6379
    password:
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://127.0.0.1:12345/api/trace
etcd:
  address: 127.0.0.1:2379

log:
  level: 'info'
  format: 'json'
  prefix: '[AAA]'
  director: './../../logs'
  encodeLevel: 'LowercaseLevelEncoder'
  linkName: 'latest_log'